service: serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: handler.list
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: handler.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: handler.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true